### ISSUE TITLE
Error Handler wont take Exception Classes

### ISSUE THREAD

**Issue by iiCarelessness** [dialtoneuk/syscrack#18]
## Your post will be deleted if the issue has already been reported!

Please search on the [issue tracker](../) before creating a new issue.

### Expected Behavior

What should happen is that I should get an error.
### Current Behavior

I get an error of an error.
### Steps to Reproduce (for bugs)

Install the game, without themes in the root directory, then go to cmd, 'php execute.php' and it'll throw the error.
### Context

I'm currently traumatised.
### Your Environment

* Version used: Latest.
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop, Windows 10
* Link to your project:

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Framework\Application\ErrorHandler::handleError() must be an instance of Exception, instance of Framework\Exceptions\ApplicationException given, called in C:\xampp\htdocs\src\Application.php on line 306 and defined in C:\xampp\htdocs\src\Application\ErrorHandler.php:56
Stack trace:
#0
C:\xampp\htdocs\src\Application.php(306): Framework\Application\ErrorHandler->handleError(Object(Framework\Exceptions\ApplicationException))
#1 C:\xampp\htdocs\execute.php(39): Framework\Application->cli(Array)
#2 {main}
  thrown in C:\xampp\htdocs\src\Application\ErrorHandler.php on line 56

Fatal error: Uncaught TypeError: Argument 1 passed to Framework\Application\ErrorHandler::handleError() must be an instance of Exception, instance of Framework\Exceptions\ApplicationException given, called in C:\xampp\htdocs\src\Application.php on line 306 and defined in C:\xampp\htdocs\src\Application\ErrorHandler.php:56
Stack trace:
#0 C:\xampp\htdocs\src\Application.php(306): Framework\Application\ErrorHandler->handleError(Object(Framework\Exceptions\ApplicationException))
#1 C:\xampp\htdocs\execute.php(39): Framework\Application->cli(Array)
#2 {main}
  thrown in C:\xampp\htdocs\src\Application\ErrorHandler.php on line 56`

**Comment by iiCarelessness** [comment]
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Framework\Application\ErrorHandler::handleError() must be an instance of Exception, instance of Framework\Exceptions\ApplicationException given, called in C:\xampp\htdocs\src\Application.php on line 306 and defined in C:\xampp\htdocs\src\Application\ErrorHandler.php:56
Stack trace:
#0
C:\xampp\htdocs\src\Application.php(306): Framework\Application\ErrorHandler->handleError(Object(Framework\Exceptions\ApplicationException))
#1 C:\xampp\htdocs\execute.php(39): Framework\Application->cli(Array)
#2 {main}
  thrown in C:\xampp\htdocs\src\Application\ErrorHandler.php on line 56`

`Fatal error: Uncaught TypeError: Argument 1 passed to Framework\Application\ErrorHandler::handleError() must be an instance of Exception, instance of Framework\Exceptions\ApplicationException given, called in C:\xampp\htdocs\src\Application.php on line 306 and defined in C:\xampp\htdocs\src\Application\ErrorHandler.php:56
Stack trace:
#0 C:\xampp\htdocs\src\Application.php(306): Framework\Application\ErrorHandler->handleError(Object(Framework\Exceptions\ApplicationException))
#1 C:\xampp\htdocs\execute.php(39): Framework\Application->cli(Array)
#2 {main}
  thrown in C:\xampp\htdocs\src\Application\ErrorHandler.php on line 56`
