### ISSUE TITLE
Flight error handler does not have access to application

### ISSUE THREAD

**Issue by iiCarelessness** [dialtoneuk/syscrack#19]
## Your post will be deleted if the issue has already been reported!

Please search on the [issue tracker](../) before creating a new issue.

### Expected Behavior

It should work x2.
### Current Behavior

It gives me an error.
### Possible Solution

Fix the code.
### Steps to Reproduce (for bugs)

Install the game, with themes in the root directory. 'php execute.php' in the cmd, wait for it to finish, visit the domain and you'll get an error.
### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

`Fatal error: Uncaught Error: Using $this when not in object context in C:\xampp\htdocs\src\Application.php:128 Stack trace: #0 C:\xampp\htdocs\vendor\mikecao\flight\flight\core\Dispatcher.php(169): Framework\Application::Framework\{closure}(Object(TypeError)) #1 C:\xampp\htdocs\vendor\mikecao\flight\flight\core\Dispatcher.php(145): flight\core\Dispatcher::callFunction(Object(Closure), Array) #2 C:\xampp\htdocs\vendor\mikecao\flight\flight\core\Dispatcher.php(49): flight\core\Dispatcher::execute(Object(Closure), Array) #3 C:\xampp\htdocs\vendor\mikecao\flight\flight\Engine.php(92): flight\core\Dispatcher->run('error', Array) #4 C:\xampp\htdocs\vendor\mikecao\flight\flight\Engine.php(185): flight\Engine->__call('error', Array) #5 [internal function]: flight\Engine->handleException(Object(TypeError)) #6 {main} thrown in C:\xampp\htdocs\src\Application.php on line 128`

**Comment by iiCarelessness** [comment]
Same thing happens when you try to create a new computer.
