### ISSUE TITLE
Error after registration

### ISSUE THREAD

**Issue by dave-4k** [dialtoneuk/Syscrack#4]
I got this Error after trying to register:

Trace:
```
#0 /src/Views/Pages/Verify.php(119): Framework\Syscrack\Game\Computers\Vpc->onStartup(1, 1, Array, Array) 
#1 /vendor/mikecao/flight/flight/core/Dispatcher.php(196): Framework\Views\Pages\Verify->page() 
#2 /vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array) 
#3 /vendor/mikecao/flight/flight/Engine.php(322): flight\core\Dispatcher::execute(Array, Array) 
#4 /vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->_start() 
#5 /vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array) 
#6 /vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array) 
#7 /vendor/mikecao/flight/flight/Engine.php(65): flight\core\Dispatcher->run('start', Array) 
#8 /vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->__call('start', Array) 
#9 /vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array) 
#10 /src/Application.php(99): Flight::__callStatic('start', Array) #11 /index.php(312): Framework\Application->runFlight() #12 {main}
```

Error:
`Call to undefined method Framework\Syscrack\Game\AddressDatabase::saveDatabase()
`

**Comment by dialtoneuk** [comment]
This has been fixed in the most recent patch.
