### ISSUE TITLE
Error in AddressDatabase.php at line 201

### ISSUE THREAD

**Issue by dave-4k** [dialtoneuk/Syscrack#6]
I got another Error if i try to execute "Example Cracker.crc":

File:
`/syscrack/src/Syscrack/Game/AddressDatabase.php at line 201`

Trace:
```
#0 /syscrack/src/Syscrack/Game/AddressDatabase.php(201): flight\Engine->handleError(2, 'Invalid argumen...', '/kunden/262564_...', 201, Array) 
#1 /syscrack/src/Syscrack/Game/Utilities/PageHelper.php(86): Framework\Syscrack\Game\AddressDatabase->hasAddress('223.72.172.193', 1) 
#2 /syscrack/views/syscrack/templates/template.tools.php(52): Framework\Syscrack\Game\Utilities\PageHelper->alreadyHacked('223.72.172.193') 
#3 /syscrack/vendor/mikecao/flight/flight/template/View.php(125): include('/kunden/262564_...') 
#4 /syscrack/vendor/mikecao/flight/flight/Engine.php(455): flight\template\View->render('syscrack/templa...', Array) 
#5 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(204): flight\Engine->_render('syscrack/templa...', Array) 
#6 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array) 
#7 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array) 
#8 /syscrack/vendor/mikecao/flight/flight/Engine.php(65): flight\core\Dispatcher->run('render', Array) 
#9 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(204): flight\Engine->__call('render', Array) 
#10 /syscrack/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array) 
#11 /syscrack/views/syscrack/page.game.internet.php(87): Flight::__callStatic('render', Array) 
#12 /syscrack/vendor/mikecao/flight/flight/template/View.php(125): include('/kunden/262564_...') 
#13 /syscrack/vendor/mikecao/flight/flight/Engine.php(455): flight\template\View->render('syscrack/page.g...', Array) 
#14 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(204): flight\Engine->_render('syscrack/page.g...', Array) 
#15 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array) 
#16 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array) 
#17 /syscrack/vendor/mikecao/flight/flight/Engine.php(65): flight\core\Dispatcher->run('render', Array) 
#18 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(204): flight\Engine->__call('render', Array) 
#19 /syscrack/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array) 
#20 /syscrack/src/Views/BaseClasses/Page.php(231): Flight::__callStatic('render', Array) 
#21 /syscrack/src/Views/Pages/Game.php(209): Framework\Views\BaseClasses\Page->getRender('page.game.inter...', Array) 
#22 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(200): Framework\Views\Pages\Game->viewAddress('223.72.172.193') 
#23 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array) 
#24 /syscrack/vendor/mikecao/flight/flight/Engine.php(322): flight\core\Dispatcher::execute(Array, Array) 
#25 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->_start() 
#26 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array) 
#27 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array) 
#28 /syscrack/vendor/mikecao/flight/flight/Engine.php(65): flight\core\Dispatcher->run('start', Array) 
#29 /syscrack/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->__call('start', Array) 
#30 /syscrack/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array) 
#31 /syscrack/src/Application.php(99): Flight::__callStatic('start', Array) 
#32 /syscrack/index.php(312): Framework\Application->runFlight() 
#33 {main}
```

Error Message:
`Invalid argument supplied for foreach()`

**Comment by dialtoneuk** [comment]
Hi ill look into this thanks!

**Comment by dialtoneuk** [comment]
This has been fixed in the most recent patch.
